// GENERATED by gen_so101_ik.py from so101_kin (so101_new_calib.urdf + base placement). Do not edit: regenerate.
// Planar model of the SO-101: see gen_so101_ik.py. All numbers are exact doubles (hex float literals).
#pragma once
#include <cstdint>
namespace so101 { namespace gen {
struct C { double re, im; };
constexpr double SIG[4] = {-0x1.0000000000000p+0, -0x1.0000000000000p+0, -0x1.0000000000000p+0, -0x1.0000000000000p+0};            // joint j in the model is exp(i * SIG[j] * q_j)
constexpr double LO[5] = {-0x1.eb7bf1e8e6080p+0, -0x1.becdf266ba494p+0, -0x1.b0a3d70a3d70ap+0, -0x1.a8769ec2ce465p+0, -0x1.5f367a0f9096cp+1};
constexpr double HI[5] = {0x1.eb7bf1e8e6080p+0, 0x1.becdf266ba494p+0, 0x1.b0a3d70a3d70ap+0, 0x1.a8769ec2ce465p+0, 0x1.6bacc4ef88b97p+1};
constexpr double LIM_C[4] = {-0x1.5e39fdfc70fecp-2, -0x1.63a20abf88724p-3, -0x1.e71a4daeafe97p-4, -0x1.64fa819fd12c8p-4};          // cos(HI): joint j is inside its limits when Re(e_j) >= LIM_C[j]
constexpr C S = {0x1.f20f345deed98p-6, 0x1.bc01a36e2eb1dp-5};                        // lift joint in the arm plane (r + i z), frame A
constexpr C L1 = {0x1.cabec7165f616p-6, 0x1.cd164ee3e65c6p-4};                       // lift -> elbow at the zero pose
constexpr C L2 = {0x1.14467381d7dbfp-3, 0x1.54c985f06f6a0p-8};                       // elbow -> wrist_flex at the zero pose
constexpr C HK[3] = {{0x1.461903dce89f7p-3, 0x1.cf36d7888c3fep-21}, {0x1.b44a34ceb79e7p-25, -0x1.02e888bd7f94cp-7}, {0x1.02512ebbb07e0p-25, -0x1.5d49c49e7ab42p-13}};                  // wrist_flex -> tip: HK[0] + cos(roll) HK[1] + sin(roll) HK[2]
constexpr double YK[3] = {-0x1.745a505f5fc80p-13, 0x1.5d49c4a532fc0p-13, -0x1.02e888bd8f118p-7};               // sideways offset of the tip from the arm plane, same form
constexpr C AK[3] = {{0x1.ffffffffbaec9p-1, 0x1.b494396d9b196p-18}, {-0x1.270018facfcf0p-36, 0x1.63bca459e529ep-19}, {-0x1.73b129b76750ep-37, 0x1.154ae5836a1c5p-23}};                  // approach direction, in-plane part, same form
constexpr double BK[3] = {0x1.ec6cdb14fde85p-19, -0x1.154ae585c2c59p-23, 0x1.63bca459f96f6p-19};               // approach direction, sideways part
constexpr C XK[3] = {{0x1.6428a6aa1a22cp-19, 0x1.2fb1b99ff57f8p-36}, {0x1.a814bfbb0c81bp-18, -0x1.ff64bafc7652bp-1}, {0x1.0b2a3d413dcafp-18, -0x1.8e9ffeed5d876p-5}};                 // jaw opening axis (tip frame x), in-plane part, same form
constexpr double XB[3] = {0x1.568ac920c8b59p-37, 0x1.8e9ffef0bd041p-5, -0x1.ff64bafc9376fp-1};              // jaw opening axis, sideways part
constexpr C E2S = {0x1.1d430eae28cd0p-2, 0x1.ebbb676de98fbp-1};                     // elbow rotation with upper arm and forearm collinear
constexpr double Q2S = -0x1.49da2900bcca7p+0;                 // ... as an elbow joint angle (the two elbow branches meet here)
constexpr double BR_HOME = -0x1.0000000000000p+0;         // elbow branch of the home pose
// upper arm + forearm as a two-link arm reaching a point at distance^2 = d2: cos(elbow from straight) = d2*HINV - SH
constexpr double P0_HINV = 0x1.fedada09b5ebcp+4, P0_SH = 0x1.02f36445fbfe0p+0, P0_K1 = 0x1.0179b222fdff0p+1, P0_K2 = -0x1.79b222fdff000p-7;
constexpr double P0_RHO = 0x1.b7f0b215b7286p-1, P0_RINV = 0x1.29ee6f811c67dp+0;       // |L1| / |L2| and its inverse
constexpr C U1[2] = {{-0x1.63a20abf88724p-3, 0x1.f838b46c52696p-1}, {-0x1.63a20abf88724p-3, -0x1.f838b46c52696p-1}};                 // lift joint at its lower / upper limit
constexpr int NE = 3;
constexpr C W2[3] = {{-0x1.e71a4daeafe97p-4, 0x1.fc5dde0b0e74ap-1}, {-0x1.e71a4daeafe97p-4, -0x1.fc5dde0b0e74ap-1}, {0x1.1d430eae28cd0p-2, 0x1.ebbb676de98fbp-1}};  // elbow at its limits (and collinear, if inside the limits)
constexpr C W3[2] = {{-0x1.64fa819fd12c8p-4, 0x1.fe0d4369c93dfp-1}, {-0x1.64fa819fd12c8p-4, -0x1.fe0d4369c93dfp-1}};                 // wrist_flex at its lower / upper limit
struct Side { double M[9]; double c[3]; double d[3]; };  // world -> frame A: M p + c ; d = straight down in frame A
constexpr Side SIDES[2] = {{{-0x1.a8958238ba9d0p-18, 0x1.ffffffffd3fd1p-1, 0x1.56f32a50e9db8p-37, -0x1.ffffffffcc3f0p-1, -0x1.a8958238bba5ep-18, 0x1.6428a6aa3a7b1p-19, 0x1.6428a6aa3f6a4p-19, 0x1.ef80551b77cbap-38, 0x1.fffffffff8420p-1}, {0x1.d09d9b9feae51p-3, -0x1.00d280c03e9d3p-2, -0x1.3096a543f9285p-1}, {-0x1.56f32a50e9db8p-37, -0x1.6428a6aa3a7b1p-19, -0x1.fffffffff8420p-1}},
                            {{-0x1.a8958238ba9d0p-18, 0x1.ffffffffd3fd1p-1, 0x1.56f32a50e9db8p-37, -0x1.ffffffffcc3f0p-1, -0x1.a8958238bba5ep-18, 0x1.6428a6aa3a7b1p-19, 0x1.6428a6aa3f6a4p-19, 0x1.ef80551b77cbap-38, 0x1.fffffffff8420p-1}, {0x1.d09f223df20f0p-3, 0x1.ac6f79606b39bp-3, -0x1.3096ce3949c39p-1}, {-0x1.56f32a50e9db8p-37, -0x1.6428a6aa3a7b1p-19, -0x1.fffffffff8420p-1}}};
constexpr int N_ATAN = 128;
constexpr double ATAN_SCALE = 0x1.6a09e667f3bccp+7;          // table index = (int)(min(|cos|,|sin|) * ATAN_SCALE)
alignas(64) constexpr double ATAN_TAB[N_ATAN + 1][4] = {  // {cos t, sin t, t, 0} at the centre of each bin
    {0x1.ffff7ffff0000p-1, 0x1.6a09e667f3bcdp-9, 0x1.6a0a04937864ap-9, 0x0.0p+0},
    {0x1.fffb7ffaeff4ap-1, 0x1.0f876ccdf6cdap-7, 0x1.0f88387524ceep-7, 0x0.0p+0},
    {0x1.fff37fd8ef0bdp-1, 0x1.c48c6001f0ac0p-7, 0x1.c4900ee5c5ec9p-7, 0x0.0p+0},
    {0x1.ffe77f69e8d15p-1, 0x1.3cc8a99af5453p-6, 0x1.3ccdb75b62364p-6, 0x0.0p+0},
    {0x1.ffd77e65cf8d0p-1, 0x1.974b2334f2347p-6, 0x1.9755e133eb070p-6, 0x0.0p+0},
    {0x1.ffc37c6c83cf6p-1, 0x1.f1cd9cceef23ap-6, 0x1.f1e13a68f7bc1p-6, 0x0.0p+0},
    {0x1.ffab7905c9284p-1, 0x1.26280b3476097p-5, 0x1.26383c503874dp-5, 0x0.0p+0},
    {0x1.ff8f73a138065p-1, 0x1.5369480174810p-5, 0x1.538228e343b84p-5, 0x0.0p+0},
    {0x1.ff6f6b962cb9fp-1, 0x1.80aa84ce72f8ap-5, 0x1.80cebe0d4e292p-5, 0x0.0p+0},
    {0x1.ff4b6023b3985p-1, 0x1.adebc19b71703p-5, 0x1.ae1e571e1c6d4p-5, 0x0.0p+0},
    {0x1.ff2350707237bp-1, 0x1.db2cfe686fe7dp-5, 0x1.db714f9c0cda1p-5, 0x0.0p+0},
    {0x1.fef73b8a8dc01p-1, 0x1.04371d9ab72fbp-4, 0x1.046401a553e06p-4, 0x0.0p+0},
    {0x1.fec720678e47fp-1, 0x1.1ad7bc01366b8p-4, 0x1.1b1167189de87p-4, 0x0.0p+0},
    {0x1.fe92fde43f35fp-1, 0x1.31785a67b5a75p-4, 0x1.31c10650c3f25p-4, 0x0.0p+0},
    {0x1.fe5ad2c48c9e2p-1, 0x1.4818f8ce34e32p-4, 0x1.48730d9f39cb1p-4, 0x0.0p+0},
    {0x1.fe1e9db35d91bp-1, 0x1.5eb99734b41efp-4, 0x1.5f27ab816bfe3p-4, 0x0.0p+0},
    {0x1.fdde5d426b562p-1, 0x1.755a359b335abp-4, 0x1.75df0ea42cfcep-4, 0x0.0p+0},
    {0x1.fd9a0fea15787p-1, 0x1.8bfad401b2968p-4, 0x1.8c9965e72bc59p-4, 0x0.0p+0},
    {0x1.fd51b40932b04p-1, 0x1.a29b726831d25p-4, 0x1.a356e06074c5cp-4, 0x0.0p+0},
    {0x1.fd0547e4de857p-1, 0x1.b93c10ceb10e2p-4, 0x1.ba17ad5ffdb74p-4, 0x0.0p+0},
    {0x1.fcb4c9a843a92p-1, 0x1.cfdcaf353049fp-4, 0x1.d0dbfc733d3b2p-4, 0x0.0p+0},
    {0x1.fc60376462f45p-1, 0x1.e67d4d9baf85bp-4, 0x1.e7a3fd68cefb7p-4, 0x0.0p+0},
    {0x1.fc078f0fd6f9dp-1, 0x1.fd1dec022ec18p-4, 0x1.fe6fe05425210p-4, 0x0.0p+0},
    {0x1.fbaace86941bep-1, 0x1.09df453456febp-3, 0x1.0a9feac8a3f81p-3, 0x0.0p+0},
    {0x1.fb49f389a5110p-1, 0x1.152f9467969c9p-3, 0x1.160a06e452327p-3, 0x0.0p+0},
    {0x1.fae4fbbee3c5fp-1, 0x1.207fe39ad63a7p-3, 0x1.21765cf975575p-3, 0x0.0p+0},
    {0x1.fa7be4b0ae86ep-1, 0x1.2bd032ce15d86p-3, 0x1.2ce505ae7eb75p-3, 0x0.0p+0},
    {0x1.fa0eabcd9959cp-1, 0x1.3720820155764p-3, 0x1.385619d5f9542p-3, 0x0.0p+0},
    {0x1.f99d4e681b72cp-1, 0x1.4270d13495143p-3, 0x1.43c9b27093aa6p-3, 0x0.0p+0},
    {0x1.f927c9b638a91p-1, 0x1.4dc12067d4b21p-3, 0x1.4f3fe8af334c0p-3, 0x0.0p+0},
    {0x1.f8ae1ad126d35p-1, 0x1.59116f9b144ffp-3, 0x1.5ab8d5f512cccp-3, 0x0.0p+0},
    {0x1.f8303eb4eeee5p-1, 0x1.6461bece53edep-3, 0x1.663493d9ea87cp-3, 0x0.0p+0},
    {0x1.f7ae324009f22p-1, 0x1.6fb20e01938bcp-3, 0x1.71b33c2c24c8dp-3, 0x0.0p+0},
    {0x1.f727f232f9366p-1, 0x1.7b025d34d329bp-3, 0x1.7d34e8f31dea8p-3, 0x0.0p+0},
    {0x1.f69d7b2fda453p-1, 0x1.8652ac6812c79p-3, 0x1.88b9b47170fe4p-3, 0x0.0p+0},
    {0x1.f60ec9b9f5fadp-1, 0x1.91a2fb9b52657p-3, 0x1.9441b92751998p-3, 0x0.0p+0},
    {0x1.f57bda354ace4p-1, 0x1.9cf34ace92036p-3, 0x1.9fcd11d4f3692p-3, 0x0.0p+0},
    {0x1.f4e4a8e6121cfp-1, 0x1.a8439a01d1a14p-3, 0x1.ab5bd97d0032ap-3, 0x0.0p+0},
    {0x1.f44931f040514p-1, 0x1.b393e935113f3p-3, 0x1.b6ee2b671cf14p-3, 0x0.0p+0},
    {0x1.f3a97156ffbb6p-1, 0x1.bee4386850dd1p-3, 0x1.c28423227ec35p-3, 0x0.0p+0},
    {0x1.f30562fc25eebp-1, 0x1.ca34879b907afp-3, 0x1.ce1ddc8890657p-3, 0x0.0p+0},
    {0x1.f25d029fa3776p-1, 0x1.d584d6ced018ep-3, 0x1.d9bb73bfa8feep-3, 0x0.0p+0},
    {0x1.f1b04bdeedb60p-1, 0x1.e0d526020fb6cp-3, 0x1.e55d053dd50c1p-3, 0x0.0p+0},
    {0x1.f0ff3a3462af6p-1, 0x1.ec2575354f54bp-3, 0x1.f102adcbb23d4p-3, 0x0.0p+0},
    {0x1.f049c8f6a6997p-1, 0x1.f775c4688ef29p-3, 0x1.fcac8a875f271p-3, 0x0.0p+0},
    {0x1.ef8ff357faee5p-1, 0x1.016309cde7484p-2, 0x1.042d5c73bfd73p-2, 0x0.0p+0},
    {0x1.eed1b4658ec88p-1, 0x1.070b316787173p-2, 0x1.0a06ab5f2b90dp-2, 0x0.0p+0},
    {0x1.ee0f0706c84b7p-1, 0x1.0cb3590126e62p-2, 0x1.0fe2411e7c7fbp-2, 0x0.0p+0},
    {0x1.ed47e5fc86d4cp-1, 0x1.125b809ac6b51p-2, 0x1.15c02cfb48b85p-2, 0x0.0p+0},
    {0x1.ec7c4be05db30p-1, 0x1.1803a83466841p-2, 0x1.1ba07e71e348cp-2, 0x0.0p+0},
    {0x1.ebac3323c717cp-1, 0x1.1dabcfce06530p-2, 0x1.2183453319d2fp-2, 0x0.0p+0},
    {0x1.ead7960f4ef99p-1, 0x1.2353f767a621fp-2, 0x1.27689125ffb89p-2, 0x0.0p+0},
    {0x1.e9fe6ec1b5945p-1, 0x1.28fc1f0145f0ep-2, 0x1.2d507269c7758p-2, 0x0.0p+0},
    {0x1.e920b72f09343p-1, 0x1.2ea4469ae5bfdp-2, 0x1.333af957aad2ap-2, 0x0.0p+0},
    {0x1.e83e691fb6f16p-1, 0x1.344c6e34858edp-2, 0x1.39283684e29fcp-2, 0x0.0p+0},
    {0x1.e7577e2f91fefp-1, 0x1.39f495ce255dcp-2, 0x1.3f183ac4aead8p-2, 0x0.0p+0},
    {0x1.e66befccd1296p-1, 0x1.3f9cbd67c52cbp-2, 0x1.450b172a6ec9dp-2, 0x0.0p+0},
    {0x1.e57bb737021dap-1, 0x1.4544e50164fbap-2, 0x1.4b00dd0bcd89fp-2, 0x0.0p+0},
    {0x1.e486cd7df2097p-1, 0x1.4aed0c9b04ca9p-2, 0x1.50f99e02fdb93p-2, 0x0.0p+0},
    {0x1.e38d2b808b220p-1, 0x1.50953434a4999p-2, 0x1.56f56bf10b4d3p-2, 0x0.0p+0},
    {0x1.e28ec9eba696ap-1, 0x1.563d5bce44688p-2, 0x1.5cf4590040ccep-2, 0x0.0p+0},
    {0x1.e18ba138d26e7p-1, 0x1.5be58367e4377p-2, 0x1.62f677a6a225dp-2, 0x0.0p+0},
    {0x1.e083a9ad0ac8dp-1, 0x1.618dab0184066p-2, 0x1.68fbdaa87df45p-2, 0x0.0p+0},
    {0x1.df76db5765f1fp-1, 0x1.6735d29b23d55p-2, 0x1.6f04951b16562p-2, 0x0.0p+0},
    {0x1.de652e0fb2b2bp-1, 0x1.6cddfa34c3a45p-2, 0x1.7510ba67626bcp-2, 0x0.0p+0},
    {0x1.dd4e9975083cap-1, 0x1.728621ce63734p-2, 0x1.7b205e4ce9bc8p-2, 0x0.0p+0},
    {0x1.dc3314ec47081p-1, 0x1.782e496803423p-2, 0x1.813394e4bac48p-2, 0x0.0p+0},
    {0x1.db12979e89f20p-1, 0x1.7dd67101a3112p-2, 0x1.874a72a47e047p-2, 0x0.0p+0},
    {0x1.d9ed187786dc3p-1, 0x1.837e989b42e01p-2, 0x1.8d650c61a6feap-2, 0x0.0p+0},
    {0x1.d8c28e23de066p-1, 0x1.8926c034e2af1p-2, 0x1.93837754c4a35p-2, 0x0.0p+0},
    {0x1.d792ef0f574e8p-1, 0x1.8ecee7ce827e0p-2, 0x1.99a5c91cf2c1ep-2, 0x0.0p+0},
    {0x1.d65e31630c748p-1, 0x1.94770f68224cfp-2, 0x1.9fcc17c36e305p-2, 0x0.0p+0},
    {0x1.d5244b037f76cp-1, 0x1.9a1f3701c21bep-2, 0x1.a5f679bf4d6e4p-2, 0x0.0p+0},
    {0x1.d3e5318e9c07fp-1, 0x1.9fc75e9b61eadp-2, 0x1.ac2505f95faa6p-2, 0x0.0p+0},
    {0x1.d2a0da59a314bp-1, 0x1.a56f863501b9dp-2, 0x1.b257d3d034291p-2, 0x0.0p+0},
    {0x1.d1573a6eff3c0p-1, 0x1.ab17adcea188cp-2, 0x1.b88efb1c4c2d4p-2, 0x0.0p+0},
    {0x1.d008468c010d0p-1, 0x1.b0bfd5684157bp-2, 0x1.beca943479a52p-2, 0x0.0p+0},
    {0x1.ceb3f31e81c99p-1, 0x1.b667fd01e126ap-2, 0x1.c50ab7f26cffcp-2, 0x0.0p+0},
    {0x1.cd5a34426b59dp-1, 0x1.bc10249b80f59p-2, 0x1.cb4f7fb774b83p-2, 0x0.0p+0},
    {0x1.cbfafdbf24051p-1, 0x1.c1b84c3520c49p-2, 0x1.d1990571714b0p-2, 0x0.0p+0},
    {0x1.ca964304dc706p-1, 0x1.c76073cec0938p-2, 0x1.d7e763a00077bp-2, 0x0.0p+0},
    {0x1.c92bf729be46bp-1, 0x1.cd089b6860627p-2, 0x1.de3ab559e2e0ap-2, 0x0.0p+0},
    {0x1.c7bc0ce6f9d71p-1, 0x1.d2b0c30200316p-2, 0x1.e49316529f4d3p-2, 0x0.0p+0},
    {0x1.c6467695b0d56p-1, 0x1.d858ea9ba0005p-2, 0x1.eaf0a2e0670a5p-2, 0x0.0p+0},
    {0x1.c4cb262bbc4dbp-1, 0x1.de0112353fcf5p-2, 0x1.f15378023f224p-2, 0x0.0p+0},
    {0x1.c34a0d384bb6ap-1, 0x1.e3a939cedf9e4p-2, 0x1.f7bbb36672621p-2, 0x0.0p+0},
    {0x1.c1c31ce05aed1p-1, 0x1.e95161687f6d3p-2, 0x1.fe297371506afp-2, 0x0.0p+0},
    {0x1.c03645dafcbabp-1, 0x1.eef989021f3c3p-2, 0x1.024e6ba21f2bap-1, 0x0.0p+0},
    {0x1.bea3786d77603p-1, 0x1.f4a1b09bbf0b1p-2, 0x1.058aff628ee5ap-1, 0x0.0p+0},
    {0x1.bd0aa467306d4p-1, 0x1.fa49d8355eda0p-2, 0x1.08ca855307d1dp-1, 0x0.0p+0},
    {0x1.bb6bb91d65013p-1, 0x1.fff1ffcefea8fp-2, 0x1.0c0d0e36cbe72p-1, 0x0.0p+0},
    {0x1.b9c6a566ab56ep-1, 0x1.02cd13b44f3c0p-1, 0x1.0f52ab3f94227p-1, 0x0.0p+0},
    {0x1.b81b57963a484p-1, 0x1.05a127811f237p-1, 0x1.129b6e120cc60p-1, 0x0.0p+0},
    {0x1.b669bd76f3335p-1, 0x1.08753b4def0afp-1, 0x1.15e768ca8bcb1p-1, 0x0.0p+0},
    {0x1.b4b1c4462a6b6p-1, 0x1.0b494f1abef26p-1, 0x1.1936ae0205335p-1, 0x0.0p+0},
    {0x1.b2f358ae2a11bp-1, 0x1.0e1d62e78ed9ep-1, 0x1.1c8950d341340p-1, 0x0.0p+0},
    {0x1.b12e66c06ae55p-1, 0x1.10f176b45ec16p-1, 0x1.1fdf64e0587d7p-1, 0x0.0p+0},
    {0x1.af62d9ef7e400p-1, 0x1.13c58a812ea8cp-1, 0x1.2338fe587b386p-1, 0x0.0p+0},
    {0x1.ad909d08a4169p-1, 0x1.16999e4dfe905p-1, 0x1.269631fe07af7p-1, 0x0.0p+0},
    {0x1.abb79a2d076cep-1, 0x1.196db21ace77cp-1, 0x1.29f7152cf5fb1p-1, 0x0.0p+0},
    {0x1.a9d7baca9b394p-1, 0x1.1c41c5e79e5f4p-1, 0x1.2d5bbde19e7afp-1, 0x0.0p+0},
    {0x1.a7f0e794913b6p-1, 0x1.1f15d9b46e46bp-1, 0x1.30c442bfe157cp-1, 0x0.0p+0},
    {0x1.a603087b63bd3p-1, 0x1.21e9ed813e2e3p-1, 0x1.3430bb1ab5d26p-1, 0x0.0p+0},
    {0x1.a40e04a46aa56p-1, 0x1.24be014e0e15bp-1, 0x1.37a13efc28b12p-1, 0x0.0p+0},
    {0x1.a211c260f39bcp-1, 0x1.2792151addfd2p-1, 0x1.3b15e72dd1ba7p-1, 0x0.0p+0},
    {0x1.a00e2724d44dbp-1, 0x1.2a6628e7ade4ap-1, 0x1.3e8ecd41c8dc9p-1, 0x0.0p+0},
    {0x1.9e03177c6d1e3p-1, 0x1.2d3a3cb47dcc2p-1, 0x1.420c0b9c245a8p-1, 0x0.0p+0},
    {0x1.9bf0770211b04p-1, 0x1.300e50814db39p-1, 0x1.458dbd7d0a2f4p-1, 0x0.0p+0},
    {0x1.99d62852cbce5p-1, 0x1.32e2644e1d9b1p-1, 0x1.4913ff0b5fbbbp-1, 0x0.0p+0},
    {0x1.97b40d026c2a5p-1, 0x1.35b6781aed828p-1, 0x1.4c9eed6023d2ap-1, 0x0.0p+0},
    {0x1.958a058edb4b7p-1, 0x1.388a8be7bd6a0p-1, 0x1.502ea6928054dp-1, 0x0.0p+0},
    {0x1.9357f1529bbfap-1, 0x1.3b5e9fb48d518p-1, 0x1.53c349c4a1c2ap-1, 0x0.0p+0},
    {0x1.911dae766d412p-1, 0x1.3e32b3815d38fp-1, 0x1.575cf73164875p-1, 0x0.0p+0},
    {0x1.8edb19e1fef1cp-1, 0x1.4106c74e2d207p-1, 0x1.5afbd03ae9412p-1, 0x0.0p+0},
    {0x1.8c900f2b9d1a4p-1, 0x1.43dadb1afd07ep-1, 0x1.5e9ff77a22f36p-1, 0x0.0p+0},
    {0x1.8a3c6886c4ebdp-1, 0x1.46aeeee7ccef6p-1, 0x1.624990cf73f07p-1, 0x0.0p+0},
    {0x1.87dffeb186a72p-1, 0x1.498302b49cd6ep-1, 0x1.65f8c17470559p-1, 0x0.0p+0},
    {0x1.857aa8e09c237p-1, 0x1.4c5716816cbe5p-1, 0x1.69adb00edf4a6p-1, 0x0.0p+0},
    {0x1.830c3caa170bcp-1, 0x1.4f2b2a4e3ca5dp-1, 0x1.6d6884c516c86p-1, 0x0.0p+0},
    {0x1.80948dee872bbp-1, 0x1.51ff3e1b0c8d4p-1, 0x1.71296953d096ap-1, 0x0.0p+0},
    {0x1.7e136ec075c93p-1, 0x1.54d351e7dc74cp-1, 0x1.74f089259a6afp-1, 0x0.0p+0},
    {0x1.7b88af4a0f4b7p-1, 0x1.57a765b4ac5c4p-1, 0x1.78be116c06c7dp-1, 0x0.0p+0},
    {0x1.78f41db0d02c2p-1, 0x1.5a7b79817c43bp-1, 0x1.7c92313ac8534p-1, 0x0.0p+0},
    {0x1.765585f7056d7p-1, 0x1.5d4f8d4e4c2b3p-1, 0x1.806d19a4e609ep-1, 0x0.0p+0},
    {0x1.73acb1daeb63dp-1, 0x1.6023a11b1c12ap-1, 0x1.844efddc3bf6dp-1, 0x0.0p+0},
    {0x1.70f968b32f83fp-1, 0x1.62f7b4e7ebfa2p-1, 0x1.8838135382161p-1, 0x0.0p+0},
    {0x1.6e3b6f4892f21p-1, 0x1.65cbc8b4bbe1ap-1, 0x1.8c2891e319cc1p-1, 0x0.0p+0},
    {0x1.6b7287ac63a2ep-1, 0x1.689fdc818bc91p-1, 0x1.9020b3f0ea1bfp-1, 0x0.0p+0},
    {0x1.689e710b78dc5p-1, 0x1.6b73f04e5bb09p-1, 0x1.9420b69b9b938p-1, 0x0.0p+0},
};
constexpr std::uint64_t GEOM_ID = 0x3fd37aedb3f4c120ULL;
}}  // namespace so101::gen
