"""Scripted baseline for the half fold: a hardcoded, open-loop movement.

Unlike QuarterFoldExpert (which re-solves IK on the live corner position and
retries a missed placement), this policy never looks at the cloth. Each arm
plays a fixed schedule of joint-space waypoints with a fixed gripper command
and a fixed number of control steps per segment:

    approach -> descend -> grasp -> lift -> carry -> place -> release -> retreat

The only feedback is the arm's own joint angles (proprio), used to servo toward
the current waypoint through joint_delta actions. So the same numbers run on
MuJoCo and on Isaac (isaac.isaac_env.make_half_fold_env).

WAYPOINTS below are hardcoded. They were solved once, offline, by `--solve`:
damped-least-squares IK on the nominal scene (cloth un-jittered, no domain
randomization) for the Cartesian targets the expert uses, including its
stage-0 OVERSHOOT. Re-run `--solve` and paste its output if the scene changes.

    python -m cloth_fold_rl.scripted_half_fold --episodes 20          # evaluate (MuJoCo)
    modal run isaac/modal_isaac.py::scripted --episodes 10            # evaluate (Isaac Sim 5.1, Modal L40S)
    python -m cloth_fold_rl.scripted_half_fold --solve                # regenerate WAYPOINTS
"""

from __future__ import annotations

import argparse

import numpy as np

from cloth_fold_rl.quarter_fold_env import HalfFoldEnv

JOINT_DELTA_SCALE = 0.05     # matches cloth_params.JOINT_DELTA_SCALE
OPEN, CLOSED = 1.0, -1.0
N_ARM_JOINTS = 5

# (segment, gripper, steps): both arms servo toward their own waypoint for that segment for `steps` control
# steps. Generated by --solve with the waypoints (each segment's largest joint move / JOINT_DELTA_SCALE, plus
# slack); do not hand-edit.
SCHEDULE = (
    ("approach", OPEN, 39),
    ("descend", OPEN, 12),
    ("grasp", CLOSED, 4),
    ("lift", CLOSED, 21),
    ("carry_1", CLOSED, 21),
    ("carry_2", CLOSED, 17),
    ("carry", CLOSED, 17),
    ("place", CLOSED, 23),
    ("hold", CLOSED, 6),
    ("release", OPEN, 4),
    ("retreat", OPEN, 14),
)

# per arm, per segment: joint targets [shoulder_pan, shoulder_lift, elbow_flex, wrist_flex, wrist_roll] (rad).
# Generated by --solve; do not hand-edit.
WAYPOINTS = {
    "left_": {
        "approach": [0.1692, 1.7453, -1.3038, -0.4807, 0.0126],
        "descend": [0.1692, 1.7233, -1.2885, -0.0881, 0.0129],
        "grasp": [0.1692, 1.7233, -1.2885, -0.0881, 0.0129],
        "lift": [0.1693, 0.9082, -0.4447, -0.2145, 0.0098],
        "carry_1": [0.1864, 0.0678, 0.3452, 0.3468, 0.0104],
        "carry_2": [0.2228, -0.4714, 0.6494, 0.9823, 0.0120],
        "carry": [0.3497, -0.6760, 0.7747, 1.6037, 0.0209],
        "place": [0.3360, -0.1578, 1.1842, 0.6748, 0.0197],
        "hold": [0.3360, -0.1578, 1.1842, 0.6748, 0.0197],
        "release": [0.3360, -0.1578, 1.1842, 0.6748, 0.0197],
        "retreat": [0.3493, -0.4344, 1.0415, 1.1300, 0.0209],
    },
    "right_": {
        "approach": [-0.1687, 1.7453, -1.3097, -0.4709, -0.0050],
        "descend": [-0.1687, 1.7230, -1.2885, -0.0881, -0.0042],
        "grasp": [-0.1687, 1.7230, -1.2885, -0.0881, -0.0042],
        "lift": [-0.1686, 0.9101, -0.4468, -0.2154, -0.0101],
        "carry_1": [-0.1863, 0.0680, 0.3453, 0.3461, -0.0098],
        "carry_2": [-0.2238, -0.4719, 0.6497, 0.9821, -0.0103],
        "carry": [-0.3549, -0.6770, 0.7746, 1.6046, -0.0183],
        "place": [-0.3406, -0.1629, 1.1847, 0.6795, -0.0187],
        "hold": [-0.3406, -0.1629, 1.1847, 0.6795, -0.0187],
        "release": [-0.3406, -0.1629, 1.1847, 0.6795, -0.0187],
        "retreat": [-0.3543, -0.4377, 1.0403, 1.1346, -0.0191],
    },
}


class ScriptedHalfFold:
    """Time-indexed open-loop policy: act() depends only on the step count and the arms' joint angles."""

    def __init__(self, env, waypoints=WAYPOINTS, schedule=SCHEDULE):
        self.base = env.unwrapped
        self.waypoints = waypoints
        self.schedule = schedule
        self.reset()

    def reset(self):
        self.t = 0

    def segment(self):
        t = self.t
        for name, grip, steps in self.schedule:
            if t < steps:
                return name, grip
            t -= steps
        name, grip, _ = self.schedule[-1]   # after the script: hold the last pose
        return name, grip

    def _arm(self, prefix, name, grip):
        q_now = np.asarray(self.base.joint_positions(prefix))[:N_ARM_JOINTS]
        q_target = np.asarray(self.waypoints[prefix][name], dtype=float)
        action = np.zeros(6, dtype=np.float32)
        action[:N_ARM_JOINTS] = np.clip((q_target - q_now) / JOINT_DELTA_SCALE, -1.0, 1.0)
        action[5] = grip
        return action

    def act(self):
        name, grip = self.segment()
        self.t += 1
        return np.concatenate([self._arm("left_", name, grip), self._arm("right_", name, grip)])


# ---- offline waypoint solve (MuJoCo only) ---------------------------------

# segment -> gripper, in order. carry_1/carry_2 are via points a third and two thirds along the carry, so the
# joint-space path stays close to the straight Cartesian one; hold keeps the corner in the jaws at the place pose
# for a few steps before the release.
SEGMENTS = (("approach", OPEN), ("descend", OPEN), ("grasp", CLOSED), ("lift", CLOSED), ("carry_1", CLOSED),
            ("carry_2", CLOSED), ("carry", CLOSED), ("place", CLOSED), ("hold", CLOSED), ("release", OPEN),
            ("retreat", OPEN))
SAME_POSE = {"grasp": "descend", "hold": "place", "release": "place"}   # only the gripper changes
DWELL = {"grasp": 4, "hold": 6, "release": 4}
SLACK = 4          # extra steps past the joint-speed bound, for the position servo to settle
# Corner placement target relative to the goal. The expert's stage-0 OVERSHOOT covers the spring-back after
# release; PLACE_OFFSET additionally covers the corner lagging the gripper in an open-loop carry (measured on
# the nominal scene, see --solve's docstring).
PLACE_OFFSET = {"left_": np.zeros(3), "right_": np.array([0.02, 0.0, 0.0])}
PLACE_HEIGHT = 0.008   # gripper site above the goal at release; the expert's 0.02 drops the corner and it springs back


def solve_waypoints(env):
    """IK for the scripted Cartesian path on the nominal scene; returns (WAYPOINTS dict, SCHEDULE tuple).

    The place pose is solved with random restarts; every other pose is seeded from its neighbour toward place
    with no restarts, so the whole path stays on one IK branch (a branch flip mid-carry swings the arm ~3 rad).
    """
    import math
    import mujoco
    from cloth_fold_rl.expert import solve_ik
    from cloth_fold_rl.fold_env import LIFT_TARGET_Z
    from cloth_fold_rl.quarter_fold_expert import OVERSHOOT

    env.unwrapped.domain_randomization = False
    env.reset(seed=0, options={"cloth_pose": np.zeros(2)})
    base = env.unwrapped
    rng = np.random.default_rng(0)
    out = {}
    for move in env.stages[0].moves:
        p = move.prefix
        corner = np.mean([env._vertex(c) for c in move.corners], axis=0)
        goal = env.goal(move) + OVERSHOOT[(0, p)] + PLACE_OFFSET[p]
        lift = np.array([corner[0], corner[1], LIFT_TARGET_Z])
        carry = np.array([goal[0], goal[1], LIFT_TARGET_Z])
        place = goal + np.array([0.0, 0.0, PLACE_HEIGHT])
        targets = {
            "approach": corner + np.array([0.0, 0.0, 0.06]),
            "descend": corner + np.array([0.0, 0.0, 0.005]),
            "lift": lift,
            "carry_1": lift + (carry - lift) / 3,
            "carry_2": lift + 2 * (carry - lift) / 3,
            "carry": carry,
            "place": place,
            "retreat": place + np.array([0.0, 0.0, 0.05]),
        }
        joint_range = [base.model.joint(f"{p}{n}").range for n in
                       ["shoulder_pan", "shoulder_lift", "elbow_flex", "wrist_flex", "wrist_roll"]]
        seed_data = mujoco.MjData(base.model)
        seed_data.qpos[:] = base.data.qpos
        out[p] = {}
        # solve the path backwards from the place pose: the near-base goal is the hard reach, so its IK branch
        # picks the whole path's branch and the far reaches inherit it
        posed = [name for name, _ in SEGMENTS if name not in SAME_POSE]
        first = posed.index("place")
        for i, name in enumerate([posed[first]] + posed[first - 1::-1] + posed[first + 1:]):
            if name == "retreat":   # forward from place again
                for k, adr in enumerate(base._arm_qpos_adr[p]):
                    seed_data.qpos[adr] = out[p]["place"][k]
            q, err = solve_ik(base.model, seed_data, base._site_id[p], base._arm_qpos_adr[p], base._arm_dof_adr[p],
                              joint_range, targets[name], rng=rng, restarts=12 if i == 0 else 1)
            print(f"  {p}{name:<8} target {np.round(targets[name], 3)} ik err {err * 100:.2f} cm")
            for k, adr in enumerate(base._arm_qpos_adr[p]):
                seed_data.qpos[adr] = q[k]
            out[p][name] = [round(float(x), 4) for x in q]
        out[p] = {name: out[p][SAME_POSE.get(name, name)] for name, _ in SEGMENTS}

    schedule = []
    prev = {p: base.joint_positions(p) for p in out}
    for name, grip in SEGMENTS:
        move = max(float(np.max(np.abs(np.array(out[p][name]) - prev[p]))) for p in out)
        steps = DWELL.get(name, math.ceil(move / JOINT_DELTA_SCALE) + SLACK)
        schedule.append((name, grip, steps))
        prev = {p: np.array(out[p][name]) for p in out}
    return out, tuple(schedule)


def format_waypoints(wp):
    lines = ["WAYPOINTS = {"]
    for p, segs in wp.items():
        lines.append(f'    "{p}": {{')
        for name, q in segs.items():
            lines.append(f'        "{name}": [{", ".join(f"{x:.4f}" for x in q)}],')
        lines.append("    },")
    lines.append("}")
    return "\n".join(lines)


def format_schedule(schedule):
    grip = {OPEN: "OPEN", CLOSED: "CLOSED"}
    return "SCHEDULE = (\n" + "".join(f'    ("{n}", {grip[g]}, {k}),\n' for n, g, k in schedule) + ")"


# ---- evaluation ----------------------------------------------------------

def run_episode(env, policy, seed):
    env.reset(seed=seed)
    policy.reset()
    for t in range(env.unwrapped.max_episode_steps):
        _, _, terminated, truncated, info = env.step(policy.act())
        if terminated or truncated:
            break
    return {"seed": seed, "steps": t + 1, "success": info["success"], "fold_score": round(info["fold_score"], 3),
            "move_distance": [round(d, 3) for d in info["move_distance"]],
            "reason": info["termination_reason"] or "truncated", "anchor_drift": round(info["anchor_drift"], 3)}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--episodes", type=int, default=20)
    ap.add_argument("--seed-base", type=int, default=0)
    ap.add_argument("--no-randomization", action="store_true", help="disable mass/friction/damping DR")
    ap.add_argument("--solve", action="store_true", help="re-solve WAYPOINTS by IK and print them")
    ap.add_argument("--isaac", action="store_true", help="evaluate on Isaac Sim (isaac.isaac_env.make_half_fold_env)")
    args = ap.parse_args()
    if args.isaac:
        from isaac.isaac_env import make_half_fold_env
        env = make_half_fold_env()
    else:
        env = HalfFoldEnv()
    if args.solve:
        waypoints, schedule = solve_waypoints(env)
        print(format_schedule(schedule))
        print(format_waypoints(waypoints))
        return
    env.unwrapped.domain_randomization = not args.no_randomization
    policy = ScriptedHalfFold(env)
    rows = []
    for i in range(args.episodes):
        row = run_episode(env, policy, args.seed_base + i)
        rows.append(row)
        print(row)
    k, n = sum(r["success"] for r in rows), len(rows)
    print(f"success {k}/{n}, mean steps {np.mean([r['steps'] for r in rows]):.0f}, "
          f"mean score {np.mean([r['fold_score'] for r in rows]):.3f}")


if __name__ == "__main__":
    main()
